#!/bin/bash
sudo chown betty hello >/dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "Successfully changed owner to betty"
else
    echo "Failed to change owner to betty"
fi
echo "New owner:"
ls -l hello | awk '{print $3}'
